### ISSUE TITLE
Ability to set a seed (or maybe a System.Random instance)?

### ISSUE THREAD

**Issue by JesseTG** [ZorPastaman/Random-Generators#1]
Hi there. I'm strongly considering using this library for probability distributions in my own game. However, I need to be able to set the initial seed for all distributions; I can't rely on `UnityEngine.Random` except for that initial seed. Is it possible to explicitly provide a seed (or a `System.Random` instance) for each generator to use?

**Comment by ZorPastaman** [comment]
Hi! All the distributions support `Func<float>` as an iid source. You can use it to get such a functionality.
I'll think about a better solution but not before the first release.

**Comment by JesseTG** [comment]
Interesting. I'll take a closer look and see if that'll let me do what I need. If not, I'll get back to you with further questions. Thank you!

**Comment by ZorPastaman** [comment]
Also, I maybe have a better solution. You can create your own IContinuousGenerator. For example, https://github.com/ZorPastaman/Random-Generators/blob/master/Runtime/ContinuousDistributions/UniformDistributions/UnityDistribution/Generators/UnityGenerator.cs. and its provider https://github.com/ZorPastaman/Random-Generators/blob/master/Runtime/ContinuousDistributions/UniformDistributions/UnityDistribution/GeneratorProviders/UnityGeneratorProvider.cs.
In this case you get all you need and default Unity serialization.

**Comment by ZorPastaman** [comment]
Hi again. In this commit https://github.com/ZorPastaman/Random-Generators/commit/19609c161095985be69ba54de0c7fb26ce261251 I added a wrapper for System.Random. You can use it directly or as a depended generator for other distributions.

**Comment by JesseTG** [comment]
Beautiful, thank you! If I have any problems I'll be sure to reach out.

**Comment by JesseTG** [comment]
Ah, looking at it there's just one thing. Is it possible you could allow us to modify the `SharpGeneratorProvider` seed (or the underlying `System.Random`) at runtime?

**Comment by ZorPastaman** [comment]
Do you mean `SharpGenerator` or exactly `SharpGeneratorProvider`?
It's pretty easy to add such a functionality to `SharpGenerator` but such a modification in `SharpGeneratorProvider` is wrong ideologically.

**Comment by JesseTG** [comment]
I don't know. How about this; why don't I describe my use case and then you can suggest something within your library that fits it? I'll do so in another thread.
