### ISSUE TITLE
Here's my use case, how would you suggest I apply your library to it?

### ISSUE THREAD

**Issue by JesseTG** [ZorPastaman/Random-Generators#2]
I opened #1 with a clear idea of my needs, but not of how they relate to this package. So I'll describe what I'm trying to do, and I'd appreciate your insight in how your library can be used for it.

I'm making a falling-block puzzle game (think Tetris or Puyo Puyo or Columns) with multiplayer. Each block has a different shape, and each shape in turn is made of pieces from a fixed set of colors. These shapes and colors are represented in my game as `ScriptableObject`s.

The set of possible shapes and colors expands at fixed intervals; this is currently done by replacing the active probability distribution with a new preset one (as opposed to modifying it in-place).

The shapes and colors are determined randomly, **but** in multiplayer mode both players must get the same sequence of pieces (including color *and* shape). It's still random, but both players get the same seed at the start of the game and both RNGs are running at the same rate.

It's okay if colors and shapes use different RNGs, or even different seeds; however, both players must get the same set of seeds at the start of the game.

I have a gut feeling that Random-Generators will better fit this use case than my current implementation, but I don't know what that would look like in practice. What would you suggest?

**Comment by ZorPastaman** [comment]
For this you need to modify a provider. I'll rewrite all the providers a little so that they all can be modified at runtime.

**Comment by JesseTG** [comment]
Perfect, thank you.

**Comment by ZorPastaman** [comment]
Look at https://github.com/ZorPastaman/Random-Generators/commit/bfd15ff0b546aa6cc3617f81ea353076cb3098f6 . I make seed in providers modifiable.

**Comment by JesseTG** [comment]
Beautiful! I can't wait to get started integrating this into my game. Thank you very much!

**Comment by ZorPastaman** [comment]
You're welcome!
