### ISSUE TITLE
[Bug] WeightedGeneratorProvider and WeightedGeneratorDependentProvider don't show their weights and values when Naughty Attributes is installed

### ISSUE THREAD

**Issue by JesseTG** [ZorPastaman/Random-Generators#3]
**Describe the bug**
When [NaughtyAttributes](https://github.com/dbrizov/NaughtyAttributes) and Random-Generators are both installed in a project, the inspector for `WeightedGeneratorProvider<T>`s and `WeightedGeneratorDependentProvider<T>`s do not draw the weights and values of the provider's distribution.

**To Reproduce**
1. Install Random-Generators.
2. Create a `WeightedGeneratorProvider<T>` or `WeightedGeneratorDependentProvider<T>` from the Assets menu. In my case, I used `IntWeightedGeneratorDependentProvider`, available through *Assets/Create/Random Generator Providers/Discrete Distributions/Weighted Distribution/Int Weighted Generator Dependent Provider*.
3. Populate the created distribution provider with your favorite values.
4. Ensure it's saved.
5. Install NaughtyAttributes.
6. Open the previously-created distribution in the inspector.
7. The values will not be visible or editable, so you won't be able to adjust them. (They will still be serialized.)

**Expected behavior**
This:

![Screenshot 2021-07-21 165600](https://user-images.githubusercontent.com/1175189/126558966-0876989d-b4df-478d-85a2-6a57114f2f05.png)

**Actual behavior**
This:

![Screenshot 2021-07-21 165801](https://user-images.githubusercontent.com/1175189/126559312-681950f6-f061-4e84-879c-f3e47f3b9cc8.png)

**Unity Editor:**
 - OS: Windows 10
 - Unity version: 2021.1.15f1
 - Package version: Random-Generators 1.3.0, Naughty Attributes 2.1.0

**Additional context**

- This issue occurs with the built-in weighted generator providers and with subclasses.
- Other generator providers are not affected.
- I don't know if this is a bug in Random-Generators or in NaughtyAttributes, so I'm reporting the issue in both projects.
- I initially believed that [Odin Inspector](https://odininspector.com/) was the culprit, but I was able to reproduce this issue in a blank project that did not have Odin installed.
- Nothing is logged and no exceptions are thrown. The custom editor simply fails silently.

**Comment by ZorPastaman** [comment]
Thank you for the report! I'll look into it. But it's strange - I simply use custom editor.

**Comment by JesseTG** [comment]
It is strange, and it might not even be a bug in this repo. That's why I cross-posted this ticket.

**Comment by ZorPastaman** [comment]
So, it was my mistake and their hack at the same time. I fixed my mistake in the new release https://github.com/ZorPastaman/Random-Generators/releases/tag/v1.3.1
Their hack is here
```
[CustomEditor(typeof(UnityEngine.Object), true)]
	public class NaughtyInspector : UnityEditor.Editor
```
So, NaughtyAttributes creates an editor for every Unity Object unless they have their own editors. But because it's not fallback, you can't create your own fallback editors.

Please, check if my fix works for you, especially if you have custom editor for classes derived from DiscreteGeneratorProvider_Base.

**Comment by JesseTG** [comment]
There's an error preventing it from being deployed to [OpenUPM](https://openupm.com/packages/com.zor.random-generators/?subPage=pipelines).

It looks like you forgot to update `package.json`.

**Comment by ZorPastaman** [comment]
Yes, my bad. I've updated it. Try it now.

**Comment by JesseTG** [comment]
No worries, it happens.

The package has successfully been deployed to OpenUPM. I'll let you know if I discover any issues with the update. Thank you!
