### ISSUE TITLE
[Feature] Document some possible uses of each distribution or other feature (especially for those who don't know the math too well)

### ISSUE THREAD

**Issue by JesseTG** [ZorPastaman/Random-Generators#4]
**Is your feature request related to a problem? Please describe.**
I find probability and statistics confusing and unintuitive; This library is easy, it's just a thin wrapper over ideas that mostly aren't. I'm already getting a lot out of some of the simpler concepts (like weighted distributions), but I bet that someone with a deep understanding of the math would get a lot out of this library.

I assume you have this deep understanding, since you wrote the thing. In college I got a C in probability.

**Describe the solution you'd like**
Documentation for each distribution (or other interesting aspect of this library) that outlines some game-related scenarios in which it would be useful. Doesn't need to be exhaustive, a couple of sentences would suffice.

**Describe alternatives you've considered**
A probability textbook.

**Additional context**
I'm assuming that you're developing this library for use in your own projects? In that case, simply writing about the things you're using this library for would go a long way.

The main impetus for me opening this issue is that I'm trying to model a particular event in my game but don't know which distribution to use. (The details probably deserve a separate thread.)

**Comment by ZorPastaman** [comment]
You're right! Though you can find that information in the Internet, it'd be more convenient to have docs right inside the project. I'll try to do something.

**Comment by ZorPastaman** [comment]
@JesseTG Better late than never:-) It's really hard to describe all the situations where you can use this or that distribution. And honestly it's unlimited. I guess it's better to do this. In Readme you can find a wikipedia link to all the distributions and there are good examples of applications there.
Also, I'm going to add a script for easy testing your distributions just to see the result.
